// Code generated by protoc-gen-go.
// source: charge_station_status.proto
// DO NOT EDIT!

package Report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChargingStationStatus struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Id        int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	// 充电站名称
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// 所属省域
	Province int32 `protobuf:"varint,4,opt,name=province" json:"province,omitempty"`
	// 所属市域
	City int32 `protobuf:"varint,5,opt,name=city" json:"city,omitempty"`
	// 所属县域
	Area int32 `protobuf:"varint,6,opt,name=area" json:"area,omitempty"`
	// 充电站地址
	Address string `protobuf:"bytes,7,opt,name=address" json:"address,omitempty"`
	// 联系人姓名
	Contacter string `protobuf:"bytes,8,opt,name=contacter" json:"contacter,omitempty"`
	// 联系人手机号
	Mobile string `protobuf:"bytes,9,opt,name=mobile" json:"mobile,omitempty"`
	// 经度
	Lat float64 `protobuf:"fixed64,10,opt,name=lat" json:"lat,omitempty"`
	// 纬度
	Lng float64 `protobuf:"fixed64,11,opt,name=lng" json:"lng,omitempty"`
	// 运营商
	OperatorId int32 `protobuf:"varint,12,opt,name=operatorId" json:"operatorId,omitempty"`
	// 运营商分成
	OperatorScale int32 `protobuf:"varint,13,opt,name=operatorScale" json:"operatorScale,omitempty"`
	// 充电桩数量
	PileNumber int32 `protobuf:"varint,14,opt,name=pileNumber" json:"pileNumber,omitempty"`
	// 空闲充电桩数量
	FreePileNumber int32 `protobuf:"varint,15,opt,name=freePileNumber" json:"freePileNumber,omitempty"`
	// 充电中充电桩数量
	WorkingPileNumber int32 `protobuf:"varint,16,opt,name=workingPileNumber" json:"workingPileNumber,omitempty"`
	// 故障充电桩数量
	ErrorPileNumber int32 `protobuf:"varint,17,opt,name=errorPileNumber" json:"errorPileNumber,omitempty"`
	// 今日充电金额 单位元
	ChargeMoneyToday float64 `protobuf:"fixed64,18,opt,name=chargeMoneyToday" json:"chargeMoneyToday,omitempty"`
	// 今日充电量 单位度
	ChargeElectricityToday float64 `protobuf:"fixed64,19,opt,name=chargeElectricityToday" json:"chargeElectricityToday,omitempty"`
}

func (m *ChargingStationStatus) Reset()         { *m = ChargingStationStatus{} }
func (m *ChargingStationStatus) String() string { return proto.CompactTextString(m) }
func (*ChargingStationStatus) ProtoMessage()    {}
