// Code generated by protoc-gen-go.
// source: charge_station_status.proto
// DO NOT EDIT!

package Report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChargingStationStatus struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Id        int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	// 充电站名称
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// 所属省域
	Province int32 `protobuf:"varint,4,opt,name=province" json:"province,omitempty"`
	// 所属市域
	City int32 `protobuf:"varint,5,opt,name=city" json:"city,omitempty"`
	// 所属县域
	Area int32 `protobuf:"varint,6,opt,name=area" json:"area,omitempty"`
	// 充电站地址
	Address string `protobuf:"bytes,7,opt,name=address" json:"address,omitempty"`
	// 联系人姓名
	Contacter string `protobuf:"bytes,8,opt,name=contacter" json:"contacter,omitempty"`
	// 联系人手机号
	Mobile string `protobuf:"bytes,9,opt,name=mobile" json:"mobile,omitempty"`
	// 经度
	Lat float64 `protobuf:"fixed64,10,opt,name=lat" json:"lat,omitempty"`
	// 纬度
	Lng float64 `protobuf:"fixed64,11,opt,name=lng" json:"lng,omitempty"`
	// 运营商
	OperatorId int32 `protobuf:"varint,12,opt,name=operatorId" json:"operatorId,omitempty"`
	// 运营商分成
	OperatorScale int32 `protobuf:"varint,13,opt,name=operatorScale" json:"operatorScale,omitempty"`
	// 充电桩数量
	PileNumber int32 `protobuf:"varint,14,opt,name=pileNumber" json:"pileNumber,omitempty"`
	// 空闲充电桩数量
	FreePileNumber int32 `protobuf:"varint,15,opt,name=freePileNumber" json:"freePileNumber,omitempty"`
	// 充电中充电桩数量
	WorkingPileNumber int32 `protobuf:"varint,16,opt,name=workingPileNumber" json:"workingPileNumber,omitempty"`
	// 开放起始时间
	OpenStartTime string `protobuf:"bytes,17,opt,name=openStartTime" json:"openStartTime,omitempty"`
	// 开放结束时间
	OpenEndTime string `protobuf:"bytes,18,opt,name=openEndTime" json:"openEndTime,omitempty"`
}

func (m *ChargingStationStatus) Reset()                    { *m = ChargingStationStatus{} }
func (m *ChargingStationStatus) String() string            { return proto.CompactTextString(m) }
func (*ChargingStationStatus) ProtoMessage()               {}
func (*ChargingStationStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ChargingStationStatus) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChargingStationStatus) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChargingStationStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChargingStationStatus) GetProvince() int32 {
	if m != nil {
		return m.Province
	}
	return 0
}

func (m *ChargingStationStatus) GetCity() int32 {
	if m != nil {
		return m.City
	}
	return 0
}

func (m *ChargingStationStatus) GetArea() int32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *ChargingStationStatus) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ChargingStationStatus) GetContacter() string {
	if m != nil {
		return m.Contacter
	}
	return ""
}

func (m *ChargingStationStatus) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ChargingStationStatus) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *ChargingStationStatus) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *ChargingStationStatus) GetOperatorId() int32 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *ChargingStationStatus) GetOperatorScale() int32 {
	if m != nil {
		return m.OperatorScale
	}
	return 0
}

func (m *ChargingStationStatus) GetPileNumber() int32 {
	if m != nil {
		return m.PileNumber
	}
	return 0
}

func (m *ChargingStationStatus) GetFreePileNumber() int32 {
	if m != nil {
		return m.FreePileNumber
	}
	return 0
}

func (m *ChargingStationStatus) GetWorkingPileNumber() int32 {
	if m != nil {
		return m.WorkingPileNumber
	}
	return 0
}

func (m *ChargingStationStatus) GetOpenStartTime() string {
	if m != nil {
		return m.OpenStartTime
	}
	return ""
}

func (m *ChargingStationStatus) GetOpenEndTime() string {
	if m != nil {
		return m.OpenEndTime
	}
	return ""
}

func init() {
	proto.RegisterType((*ChargingStationStatus)(nil), "Report.ChargingStationStatus")
}

func init() { proto.RegisterFile("charge_station_status.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0xe5, 0x5e, 0xd2, 0x66, 0x7a, 0x8d, 0x8f, 0x7a, 0x34, 0x88, 0x4d, 0xc4, 0x2a, 0x2b,
	0x36, 0x3c, 0x02, 0x62, 0xc1, 0x06, 0x21, 0xca, 0x1e, 0xb9, 0xce, 0x10, 0x2c, 0x12, 0xdb, 0x9a,
	0xb8, 0x20, 0x5e, 0x96, 0x67, 0x41, 0x19, 0x54, 0xd1, 0x95, 0xf5, 0x7d, 0xf3, 0xdb, 0x1e, 0xfd,
	0x70, 0x69, 0xdf, 0x0c, 0x37, 0xf4, 0xd2, 0x27, 0x93, 0x5c, 0xf0, 0x72, 0x1e, 0xfb, 0xeb, 0xc8,
	0x21, 0x05, 0x9d, 0x3d, 0x51, 0x0c, 0x9c, 0xae, 0xbe, 0x47, 0xb0, 0xbb, 0x1d, 0x72, 0xce, 0x37,
	0xfb, 0xdf, 0xe0, 0x5e, 0x72, 0xba, 0x80, 0xfc, 0xd9, 0x75, 0xd4, 0x27, 0xd3, 0x45, 0x54, 0xa5,
	0xaa, 0x26, 0x1a, 0x60, 0xe4, 0x6a, 0x1c, 0x95, 0xaa, 0x9a, 0xea, 0x25, 0x4c, 0xbc, 0xe9, 0x08,
	0xc7, 0xa5, 0xaa, 0x72, 0xbd, 0x85, 0x79, 0xe4, 0xf0, 0xe1, 0xbc, 0x25, 0x9c, 0x9c, 0xe6, 0xd6,
	0xa5, 0x2f, 0x9c, 0x9e, 0xc8, 0x30, 0x19, 0xcc, 0x84, 0x36, 0x30, 0x33, 0x75, 0xcd, 0xd4, 0xf7,
	0x38, 0x93, 0xeb, 0x05, 0xe4, 0x36, 0xf8, 0x64, 0x6c, 0x22, 0xc6, 0xb9, 0xa8, 0x35, 0x64, 0x5d,
	0x38, 0xb8, 0x96, 0x30, 0x17, 0x5e, 0xc0, 0xb8, 0x35, 0x09, 0xa1, 0x54, 0x95, 0x12, 0xf0, 0x0d,
	0x2e, 0x04, 0x34, 0x40, 0x88, 0xc4, 0x26, 0x05, 0xbe, 0xaf, 0x71, 0x29, 0x3f, 0xec, 0x60, 0x75,
	0x72, 0x7b, 0x6b, 0x5a, 0xc2, 0x95, 0x68, 0x0d, 0x10, 0x5d, 0x4b, 0x0f, 0xc7, 0xee, 0x40, 0x8c,
	0x6b, 0x71, 0xff, 0x61, 0xfd, 0xca, 0x44, 0x8f, 0x7f, 0x7e, 0x23, 0xfe, 0x02, 0x8a, 0xcf, 0xc0,
	0xef, 0xce, 0x37, 0x67, 0xa3, 0xed, 0xd9, 0xeb, 0x43, 0x51, 0x9c, 0x86, 0x8e, 0xb0, 0x90, 0x15,
	0xff, 0xc1, 0x62, 0xd0, 0x77, 0xbe, 0x16, 0xa9, 0x07, 0x79, 0xc8, 0xa4, 0xef, 0x9b, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x16, 0xf9, 0x9d, 0x60, 0x8e, 0x01, 0x00, 0x00,
}
